### PR TITLE
fix(importIED): Fix EnumType order on IED import, part of #47

### LINKED ISSUE #47: tIED: insertIed incorrectly orders elements within the DataTypeTemplates
Similar to #46, it seems to be possible to incorrectly add DataTypeTemplates and create a schema invalid file.

I've seen for example the following in my DataTypeTemplate section:

```xml
<LNodeType id="SIPROTEC5_LNType_ATCC_Parallel_Goose_Proxy" lnClass="ATCC">
      <DO name="Mod" type="SIPROTEC5_DOType_Mod_controllable_with_InitValVis_for_SIEMENS_LN_V09.50.01_V09.50.01"/>
      <DO name="Blk" type="SIPROTEC5_DOType_SPS_for_Input_V09.50.01_V09.50.01"/>
      <DO name="Auto" type="SIPROTEC5_DOType_SPC_ATCC_Auto_V09.50.01_V09.50.01"/>
      <DO name="ParOp" type="SIPROTEC5_DOType_SPC_statusOnly_and_dir_with_nor_sec_V09.50.01_V09.50.01"/>
      <DO name="TapChg" type="SIPROTEC5_DOType_BSC_controllable_without_BinaryInput_V09.50.01_V09.50.01"/>
      <DO name="CtlV" type="SIPROTEC5_DOType_MV_Float_V09.50.01_V09.50.01"/>
      <DO name="LodA" type="SIPROTEC5_DOType_MV_Float_V09.50.01_V09.50.01"/>
      <DO name="PhAng" type="SIPROTEC5_DOType_MV_Float_V09.50.01_V09.50.01"/>
      <DO name="Beh" type="SIPROTEC5_DOType_ENS_Behavior_V09.50.01_V09.50.01"/>
      <DO name="Health" type="SIPROTEC5_DOType_ENS_Health_V09.50.01_V09.50.01"/>
      <DO name="NamPlt" type="SIPROTEC5_DOType_LPL_NamPlt_for_Ed2_LN_V09.50.01_V09.50.01"/>
      <DO name="RHealth" type="SIPROTEC5_DOType_INS_INT32_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="ParGrp" type="SIPROTEC5_DOType_INC_controllable_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="PTrfBeh" type="SIPROTEC5_DOType_INS_INT32_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="PTrfId" type="SIPROTEC5_DOType_INS_INT32_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="IncParGrp" type="SIPROTEC5_DOType_SPS_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="PaAutoBlk" type="SIPROTEC5_DOType_SPS_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="ErrTapDif" type="SIPROTEC5_DOType_SPS_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="RxRHealth1" type="SIPROTEC5_DOType_INS_INT32_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="RxBlk1" type="SIPROTEC5_DOType_SPS_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="RxAuto1" type="SIPROTEC5_DOType_ComProxy_SPC_V09.50.01_V09.50.01"/>
      <DO name="RxParOp1" type="SIPROTEC5_DOType_ComProxy_SPC_V09.50.01_V09.50.01"/>
      <DO name="RxParGrp1" type="SIPROTEC5_DOType_ComProxy_INC_V09.50.01_V09.50.01"/>
      <DO name="RxPTrfBeh1" type="SIPROTEC5_DOType_INS_INT32_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="RxTapChg1" type="SIPROTEC5_DOType_ComProxy_BSC_V09.50.01_V09.50.01"/>
      <DO name="RxPTrfId1" type="SIPROTEC5_DOType_INS_INT32_with_dataNs_V09.50.01_V09.50.01"/>
      <DO name="RxCtlV1" type="SIPROTEC5_DOType_ComProxy_MV_V09.50.01_V09.50.01"/>
      <DO name="RxInvX1" type="SIPROTEC5_DOType_ComProxy_MV_V09.50.01_V09.50.01"/>
      <DO name="RxLodA1" type="SIPROTEC5_DOType_ComProxy_MV_V09.50.01_V09.50.01"/>
      <DO name="RxPhAng1" type="SIPROTEC5_DOType_ComProxy_MV_V09.50.01_V09.50.01"/>
    </LNodeType><EnumType id="SIPROTEC5_Textlist_POWCap_V09.50.01_V09.50.01">
      <EnumVal ord="1">None</EnumVal>
      <EnumVal ord="2">Close</EnumVal>
      <EnumVal ord="3">Open</EnumVal>
      <EnumVal ord="4">Close and Open</EnumVal>
    </EnumType>
```

Here is an example file I've prepared after opening an ICD file with a 7SL86 device in it and then using the "Import Templates" plugin to add a SEL-487E-5 device.

There are many schema errors which seem to stem from either incorrectly ordered elements or perhaps a few missing elements.

image

[Siprotec_7SL86_Base (1) (2).icd.zip](https://github.com/OpenEnergyTools/scl-lib/files/12653888/Siprotec_7SL86_Base.1.2.icd.zip)

I have not figured out exactly what is happening here. If it's not obvious I can look at this in more detail.

### PR DESCRIPTION
**Pull request by danyill**
Closes #47

### CODE REVIEW

File: tIED/insertIED.ts [hunk 1]
```diff
@@ -133,7 +133,7 @@ function addEnumType(
   return {
     parent: oldDataTypeTemplates,
     node: newEnumType,
-    reference: getReference(oldDataTypeTemplates, "LNodeType"),
+    reference: getReference(oldDataTypeTemplates, "EnumType"),
```
Comment (danyill) [inline tIED/insertIED.ts:136]: This is really the only thing to see here :wink:

Comment (JakobVogelsang) [reply tIED/insertIED.ts:136]: Uff I am sorry! I did miss this as the order has been checked for and empty SCL! Great!

File: tIED/insertIED.spec.ts [hunk 2]
```diff
@@ -174,4 +180,29 @@ describe("Function to an importIED and its referenced elements", () => {
...
+    const scl = (
+      await fetch("tIED/importIED/emptyproject.scd")
+        .then((response) => response.text())
+        .then((str) => new DOMParser().parseFromString(str, "application/xml"))
+    ).querySelector("SCL")!;
+
+    const firstIedImports = insertIed(scl, validIed);
+    handleEdit(firstIedImports);
+
+    const secondIedImports = insertIed(scl, anotherValidIed);
```
Comment (JakobVogelsang) [inline tIED/insertIED.spec.ts:194]: I would be careful with this! The function `importIed` is not aiming to support multi IED import. We cannot give this promise. It is very likely that it will work this way, as handleEdit takes less time to do stuff compared to the constructing of the Edit[]. Still, to make this clear, I would love to leave tests doing multi IED import out of this function spec. 
There will be an `importIEDs` function exported. Initially I did try to have such a function but failed due to the complexity coming with it. 
For now I would ask you to have those tests be part of your repository and when the `importIEDs` function is available you can switch and remove those.

Comment (JakobVogelsang) [reply tIED/insertIED.spec.ts:194]: Bwt. the regression test here can be done with a simple IED import by importing to and IED with existing `DOType` and an `EnumType` being copied over.

File: tIED/importIED/valid.iid [hunk 3]
```diff
@@ -48,10 +54,8 @@
 			</ConnectedAP>
 		</SubNetwork>
 	</Communication>
-	<IED name="TestImportIED" type="TestType" manufacturer="TestMan" originalSclVersion="2007" originalSclRevision="B" originalRelease="4" eTest2:New="fancy new attribute">
-		<NewThing>
-			<P type="solution" />
-		</NewThing>
+	<IED name="TestImportIED" type="TestType" manufacturer="TestMan" originalSclVersion="2007"
```
Comment (JakobVogelsang) [inline tIED/importIED/valid.iid:57]: Those as automated formatting issues is that? Or are those changes needed to the tests?

**Review by JakobVogelsang — CHANGES_REQUESTED** [review]
@danyill I am sorry, but I have to request changes. Maybe I am too strict at the moment :(

**Comment by JakobVogelsang** [comment]
One more thing: I would love to have one commit per issue. With this PR I have the impression this one fix and would expect one commit.

File: tIED/importIED/valid.iid (hunk 3 above)
Comment (danyill) [reply tIED/importIED/valid.iid:57]: Well, `NewThing` is schema invalid...

File: tIED/insertIED.spec.ts (hunk 2 above)
Comment (danyill) [reply tIED/insertIED.spec.ts:194]: Sure, I'll adjust for that.

**Comment by danyill** [comment]
I have made this PR more restricted. Far better to have some strict rules and order than a chaotic history. I must be a little more precise! :+1: 

My original concern was that the `valid.iid` was in fact, not schema valid making it difficult to sort out where the problem was for me but that should perhaps be dealt with separately.

And I forgot about the one commit per issue in the repo, I am sorry :disappointed:

**Comment by JakobVogelsang** [comment]
LGTM thank you!!

two little thing I would ask you to change:

1 rename the commit to stick with conventional commit syntax. fix(importIED): ...
2 the name of the doc in the test you have touched could be changed to. That would read better I think

**Comment by danyill** [comment]
> LGTM thank you!!
> 
> two little thing I would ask you to change:
> 
> 1 rename the commit to stick with conventional commit syntax. fix(importIED): ... 2 the name of the doc in the test you have touched could be changed to. That would read better I think

Quite right, done!

**Review by JakobVogelsang — APPROVED** [review]
LGTM
