### PR TITLE
fix(foundation/nsd): Improve nsd import in dependent libraries

### LINKED ISSUE #28: Error when using this library in another project
I can't integrate the current version of scl-lib in my project due to MIME typing checking. I receive the following console error when using scl-lib version 0.1.0 for `nsd.json`

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/json". Strict MIME type checking is enforced for module scripts per HTML spec.

image

### PR DESCRIPTION
**Pull request by danyill**
Closes #28

This almost works but I can't get the tests to pass:

```
tExtRef/extRefTypeRestrictions.spec.ts:

 🚧 Browser logs:
      SyntaxError: Unexpected token 'v', "var NamPlt"... is not valid JSON

 ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information. 
```

I think this is because "somehow" a sourcemap is included with this json file which I must still examine.

### CODE REVIEW

File: tExtRef/extRefTypeRestrictions.ts [hunk 1]
```diff
@@ -1,4 +1,16 @@
...
+    throw new Error(
+      `Failed to fetch JSON file: ${path.toString()} ${response.status} ${
+        response.statusText
+      }`
+    );
+  }
+  return await response.json();
+}
+
+const dataObjects = await fetchJSON("../foundation/nsd.json");
```
Comment (ca-d) [inline tExtRef/extRefTypeRestrictions.ts:13]: What's the functional difference between this and

```suggestion
const dataObjects = await fetch(new URL("../foundation/nsd.json", import.meta.url)).then(res => res.json());
```

apart from the custom error message? I'm asking quite naively, I assume that both would just result in a rejected promise in case of either a non-ok response or invalid json, but I haven't tried. If and only if there is a significant functional advantage I would keep the custom function, otherwise I'd probably prefer the one-liner for readability.

**Review by ca-d — APPROVED** [review]
LGTM, great detective work figuring out how to wrangle the impertinent build tool! :mag:

File: tExtRef/extRefTypeRestrictions.ts (hunk 1 above)
Comment (danyill) [reply tExtRef/extRefTypeRestrictions.ts:13]: I agree, let's do that.

**Comment by danyill** [comment]
Thank you for reviewing. I have squashed and added the suggestion (as Jakob would like to use rebase on this project rather than merge)

**Review by JakobVogelsang — APPROVED** [review]
LGMT

I have learned as well a bit more about the fetch API
